### ISSUE TITLE
M_2_6_01_TOOL

### ISSUE THREAD

**Issue by metaphorz** [generative-design/Code-Package-Processing-3.x#1]
M_2_6_01_TOOL.pde gives the error "addComponentListener(FrameListener) when
launched in the most recent version of P3. If this is a known issue, I'll wait until a fix.
Otherwise, I may not have all of the required libs? I have controlP5 from the github
repository: controlP5-2.2.5

Thanks for your efforts to make the code P3 compatible.

**Comment by b-g** [comment]
Hi @metaphorz, Many thanks for the feedback! However this entire repo (3.x code) is work in progress and is currently not supported by us as P3 is still in beta. I'm sorry ... but we are on it. In the meantime please use the stable code packages (2.x). All the best, Benedikt
