### ISSUE TITLE
Extra loop in for statement

### ISSUE THREAD

**Issue by andrta** [generative-design/Code-Package-Processing-3.x#5]
Hey, I just noticed that there is an extra loop in the `for` statement in line 75, mentioned in the link below.
If I'm not mistaken, it seems that the variable `i` should be initialized with `rowCount - 1`.

`for(int i = rowCount - 1; i >= 0; i--) {
 ...`

I hope this comment can help. Thanks a lot for the amazing Generative Design book and this connected repository! 

https://github.com/generative-design/Code-Package-Processing-3.x/blob/1bb3dd342bcada8b09c9e5f91c20613c7f11d69f/01_P/P_1_2_3_03/P_1_2_3_03.pde#L75

**Comment by bohnacker** [comment]
Hi @andrta,
thanks for pointing that out! You're right, this is an extra loop. But it isn't very obvious since rowCount is a random number in our example. I fixed it in this repo but will only update the releases if there were more changes.
And thanks a lot that you like the book! 😀👍
